name: publish package
description: publish a package to PyPI
inputs:
  pypi-auth-token:
    description: 'PyPI token for authorization'
    required: true

runs:
  using: composite
  steps:
    - name: Publish package
      shell: bash
      run: uv publish --token ${{ inputs.pypi-auth-token }}
